load("@crates//:defs.bzl", "all_crate_deps")
load("//:version.bzl", "MORI_VERSION")
load("@rules_rust//cargo:extract_cargo_lints.bzl", "extract_cargo_lints")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

extract_cargo_lints(
    name = "lints",
    manifest = "Cargo.toml",
    workspace = "//:Cargo.toml",
)

rust_binary(
    name = "mori",
    version = MORI_VERSION,
    srcs = glob(["src/**/*.rs"]),
    lint_config = ":lints",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    visibility = ["//visibility:public"],  # the Python e2e tests depend on it
    deps = all_crate_deps(normal = True) + [
        "//crates/api:mori_api",
        "//crates/app:mori_app",
        "//crates/core:mori_core",
        "//crates/git:mori_git",
        "//crates/github:mori_github",
        "//crates/jj:mori_jj",
    ],
)

rust_test(
    name = "mori_unit_test",
    size = "small",
    crate = ":mori",
    lint_config = ":lints",
    deps = all_crate_deps(normal_dev = True),
)

rust_test(
    name = "cli_test",
    version = MORI_VERSION,
    size = "small",
    srcs = ["tests/cli.rs"],
    data = [":mori"],
    lint_config = ":lints",
    rustc_env = {"CARGO_BIN_EXE_mori": "$(rootpath :mori)"},
    deps = all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
