load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//cargo:extract_cargo_lints.bzl", "extract_cargo_lints")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

extract_cargo_lints(
    name = "lints",
    manifest = "Cargo.toml",
    workspace = "//:Cargo.toml",
)

rust_library(
    name = "mori_core",
    srcs = glob(["src/**/*.rs"]),
    lint_config = ":lints",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "mori_core_test",
    size = "small",
    crate = ":mori_core",
    lint_config = ":lints",
)
