load("@crates//:defs.bzl", "all_crate_deps")
load("//:version.bzl", "MORI_VERSION")
load("@rules_rust//cargo:extract_cargo_lints.bzl", "extract_cargo_lints")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

extract_cargo_lints(
    name = "lints",
    manifest = "Cargo.toml",
    workspace = "//:Cargo.toml",
)

rust_library(
    name = "mori_store",
    version = MORI_VERSION,
    srcs = glob(["src/**/*.rs"]),
    compile_data = ["//skills:files"],
    lint_config = ":lints",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(normal = True) + ["//crates/core:mori_core"],
)

rust_test(
    name = "mori_store_test",
    size = "small",
    compile_data = ["//skills:files"],
    crate = ":mori_store",
    lint_config = ":lints",
    deps = all_crate_deps(normal_dev = True),
)
